import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

import { Footer } from "@/app/components/footer.tsx"
import { Header } from "@/app/components/header.tsx"

import { UserProvider } from "@auth0/nextjs-auth0/client"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <main>
            <Header></Header>
            {children}
          </main>
          <Footer></Footer>
        </body>
      </UserProvider>
    </html>
  )
}
